routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PemasokController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\DetailKondisiController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\AsistenLabController;
use App\Http\Controllers\AsistenList;
use App\Http\Controllers\PraktikumController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\JadwalUserController;
use App\Http\Controllers\PengajuanJadwalController;
use App\Http\Controllers\ProfileAslabController;
use App\Http\Controllers\BapController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\BapPraktikumController;
use App\Models\Mahasiswa;
use Illuminate\Support\Facades\Auth;
use App\Models\Matakuliah;
use App\Models\PengajuanJadwal;
use App\Models\Praktikum;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::view('/', 'landingpage.index');

Route::get('/', [LandingPageController::class, 'index'])->name('index');

Route::view('/about', 'landingpage/about')->name('about');
Route::view('/contact', 'landingpage/contact')->name('contact');
Route::view('/error', 'errors.403')->name('error.403');

// Route::get('/login', function () {
//     return view('auth.login');
// })->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::view('/', 'landingpage/index')->name('index');
// Route::view('/about', 'landingpage/about')->name('about');
// Route::view('/contact', 'landingpage/contact')->name('contact');
// Route::view('/error', 'errors.403')->name('error.403');


Route::get('/login', function () {
    if (Auth::check()) {
        return redirect()->route('index'); // Redirect to home page
    } else {
        return view('auth.login');
    }
})->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::get('/jadwal-praktikum', [JadwalUserController::class, 'index'])->name('jadwal-praktikum');
Route::resource('jadwal-praktikum', JadwalUserController::class);
Route::resource('asisten', AsistenList::class);

Route::group(['middleware' => ['auth']], function () {
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA'])->group(function () {
    Route::resource('pengguna', PenggunaController::class);

    Route::resource('dosen', DosenController::class);

    Route::resource('matakuliah', MatakuliahController::class);

    Route::resource('aslab', AsistenLabController::class);

    Route::resource('detail-kondisi', DetailKondisiController::class, ['except' => [
        'create', 'update', 'show'
    ]]);
    Route::resource('inventory', InventoryController::class, ['except' => [
        'create', 'update', 'show'
    ]]);

    Route::resource('pemasok', PemasokController::class);

    Route::resource('mahasiswa', MahasiswaController::class);

    Route::resource('kategori', KategoriBarangController::class);

    Route::get('kategori', [KategoriBarangController::class, 'list_categories'])->name('kategori.list');

    Route::get('tambah-barang', [InventoryController::class, 'add']);
    Route::post('tambah-barang/save', [InventoryController::class, 'save']);
    Route::get('edit-barang/{id}', [InventoryController::class, 'edit']);
    Route::get('detail-barang/{id}', [InventoryController::class, 'detail']);
    Route::delete('delete-barang/{id}', [InventoryController::class, 'delete']);
    Route::get('detail-kondisi/{id}', [InventoryController::class, 'detail_kondisi']);
    Route::delete('delete-all-detail-kondisi/{id_barang}/{id}', [InventoryController::class, 'delete_all_detail_kondisi']);
    Route::post('add-detail-kondisi/{id}', [InventoryController::class, 'add_detail_kondisi']);

    Route::get('pengguna/export', [PenggunaController::class, 'export'])->name('pengguna.export');
    Route::post('pengguna/import', [PenggunaController::class, 'import'])->name('pengguna.import');

    Route::post('matakuliah/import', [MatakuliahController::class, 'import'])->name('matakuliah.import');
    // Route::get('jadwal', [JadwalController::class, 'index']);
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN'])->group(function () {

    Route::get('profile-aslab', [ProfileAslabController::class, 'index'])->name('profile.aslab');
    // Route::get('profile-aslab/{id}',[ProfileAslabController::class, 'edit'])->name('profile.aslab.update');
    Route::put('/profile-aslab/{id}', [ProfileAslabController::class, 'edit'])->name('profile.aslab.update');

    // Route::post('profile-aslab',[AsistenLabController::class],'profileEditAslab');

    Route::get('/getKodePraktikum/{nrp}/{id_user}', [PengajuanJadwalController::class, 'getKodePraktikum']);

    Route::resource('pengajuan-jadwal', PengajuanJadwalController::class);
    Route::post('/terima-pengajuan/{id}', [PengajuanJadwalController::class, 'terimaPengajuan'])->name('terima.pengajuan');
    Route::post('/tolak-pengajuan/{id}', [PengajuanJadwalController::class, 'tolakPengajuan'])->name('tolak.pengajuan');
    Route::post('/tambah-jadwal/{id}', [PengajuanJadwalController::class, 'tambahJadwal'])->name('tambah.jadwal');

 
    // Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    // Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
   
    // Route::get('/bap', [BapPraktikumController::class, 'index'])->name('bap-praktikum.list');
    // Route::get('/bap/{kode_praktikum}', [BapPraktikumController::class, 'listBap'])->name('bap-praktikum.list');
    // Route::post('/bap/store', [BapPraktikumController::class, 'storeBap'])->name('bap-praktikum.store');
    // Route::delete('/bap/delete/{id}', [BapPraktikumController::class, 'deleteBap'])->name('bap-praktikum.delete');
    // Route::post('bap/validate/asisten', [BapPraktikumController::class, 'validateAsisten'])->name('validasi.asisten');
    // Route::post('bap/validate/mahasiswa', [BapPraktikumController::class, 'validateMhs'])->name('validasi.mahasiswa');


});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,KOORDINATOR'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('jadwal', JadwalController::class);

    Route::resource('praktikum', PraktikumController::class);

    Route::get('/praktikum/asisten/{kode_praktikum}', [PraktikumController::class, 'asisten'])->name('praktikum.asisten');
    Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
 
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN,KOORDINATOR,MAHASISWA'])->group(function () {
    Route::get('/bap', [BapController::class, 'index'])->name('bap.list');
    Route::get('/bap/{kode_praktikum}', [BapController::class, 'list'])->name('bap.topik');
    // Route::post('/bap/store', [BapController::class, 'storeBap'])->name('bap.store');
    // Route::delete('/bap/delete/{id}', [BapController::class, 'deleteBap'])->name('bap.delete');
    Route::post('/bap/validate', [BapController::class, 'validateBap'])->name('bap.validate');
    Route::post('/bap/validateMhs', [BapController::class, 'validateMahasiswa'])->name('bap.validateMhs');
    // Route::get('bap/{id}/edit', [BapController::class, 'edit']);
    Route::resource('bap', BapController::class);
    Route::post('/custom-pdf-data', [BapController::class, 'getCustomPdfData'])->name('custom_pdf_data_endpoint');

});

app/Models/Jadwal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Jadwal extends Model
{
    use HasFactory;
    protected $table = "jadwal";
    protected $fillable=['kode_jadwal','kode_praktikum','hari','jam_mulai','jam_berakhir','ruang','durasi'];

    public function praktikum()
    {
        return $this->belongsTo(Praktikum::class, 'kode_praktikum','kode_praktikum');
    }

    public function matakuliah()
    {
        return $this->belongsTo(Matakuliah::class, 'kode_matakuliah', 'kode_matakuliah');
    }
}

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Matakuliah;
use App\Models\Jadwal;
use App\Models\Praktikum;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Str;
use Carbon\Carbon;

class JadwalController extends Controller
{
    public function index(Request $request)
    {
        $praktikum = Praktikum::join('matakuliah', 'praktikum.kode_matakuliah', '=', 'matakuliah.kode_matakuliah')
            ->select('praktikum.kode_praktikum', 'praktikum.kode_matakuliah', 'praktikum.kelas', 'matakuliah.nama_matakuliah')
            ->get()
            ->toArray();
        $existingKodePraktikum = Jadwal::pluck('kode_praktikum')->toArray();

        if ($request->ajax()) {
            $data = Jadwal::with(['praktikum.matakuliah'])->latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('kode_matakuliah', function ($row) {
                    return $row->praktikum->kode_matakuliah ?? '';
                })
                ->addColumn('kelas', function ($row) {
                    return $row->praktikum->kelas ?? '';
                })

                ->addColumn('nama_matakuliah', function ($row) {
                    return $row->praktikum->matakuliah->nama_matakuliah ?? '';
                })

                ->addColumn('aksi', function ($row) {
                    $btn = '<a href="javascript:void(0)" data-id="' . $row->id . '" class="edit btn btn-warning btn-sm editData"><i class="fa fa-edit"></i>&nbsp;Edit</a>';
                    $btn .= ' <a href="javascript:void(0)" data-id="' . $row->id . '" class="btn btn-danger btn-sm deleteData" data-url="' . route('jadwal.store') . '"><i class="fa fa-trash"></i>&nbsp;Delete</a>';
                    return $btn;
                })
                ->rawColumns(['kode_matakuliah', 'nama_matakuliah', 'kelas', 'aksi'])
                ->make(true);
        }

        return view('jadwal.list', ["praktikum" => $praktikum, "existingKodePraktikum" => $existingKodePraktikum]);
    }

    public function store(Request $request)
    {
        $kodeJadwal = $this->generateJadwalId();
        $hari = $request->hari;
        $ruang = $request->ruang;
        $jamMulai = $request->jam_mulai;
        $jamBerakhir = $this->calculateEndTime($jamMulai, $request->durasi);
    
        if (!empty($request->id)) {
            $data = Jadwal::find($request->id);
            $cekBentrok = $this->cekJadwalBentrok($jamMulai, $jamBerakhir, $hari, $ruang, $request->id);
            if ($cekBentrok) {
                return response()->json(['error' => $cekBentrok], 400);
            }
            $data->kode_praktikum = $request->kode_praktikum;
            $data->hari = $request->hari;
            $data->jam_mulai = $request->jam_mulai;
            $data->jam_berakhir = $this->calculateEndTime($request->jam_mulai, $request->durasi);
            $data->ruang = $request->ruang;
            $data->durasi = $request->durasi;
            $data->save();
        
            $jumlahPertemuan = 0;
        
            if ($request->durasi == 200) {
                $jumlahPertemuan = 14;
            } elseif ($request->durasi == 160) {
                $jumlahPertemuan = 16;
            } elseif ($request->durasi == 170) {
                $jumlahPertemuan = 15;
            }
        
            if ($jumlahPertemuan > 0) {
                $praktikum = Praktikum::where('kode_praktikum', $request->kode_praktikum)->first();
                if ($praktikum) {
                    $praktikum->jumlah_week = $jumlahPertemuan;
                    $praktikum->save();
                }
            }
        } else {
            // // Memeriksa apakah kode_matakuliah dan kelas sudah ada di database
            $existingData = Jadwal::where('kode_praktikum', $request->kode_praktikum)
                ->first();
    
            if ($existingData) {
                return response()->json(['error' => 'Jadwal Praktikum sudah ada'], 422);
            }
    
            $cekBentrok = $this->cekJadwalBentrok($jamMulai, $jamBerakhir, $hari, $ruang);
            if ($cekBentrok) {
                return response()->json(['error' => $cekBentrok], 400);
            }
            
            Jadwal::create([
                'kode_jadwal' => $kodeJadwal,
                'kode_praktikum' => $request->kode_praktikum,
                'hari' => $request->hari,
                'jam_mulai' => $request->jam_mulai,
                'jam_berakhir' => $jamBerakhir,
                'ruang' => $request->ruang,
                'durasi' => $request->durasi,
            ]);
    
            $jumlahPertemuan = 0;
    
            if ($request->durasi == 200) {
                $jumlahPertemuan = 14;
            } elseif ($request->durasi == 160) {
                $jumlahPertemuan = 16;
            } elseif ($request->durasi == 170) {
                $jumlahPertemuan = 15;
            }
    
            if ($jumlahPertemuan > 0) {
                $praktikum = Praktikum::where('kode_praktikum', $request->kode_praktikum)->first();
                if ($praktikum) {
                    $praktikum->jumlah_week = $jumlahPertemuan;
                    $praktikum->save();
                }
            }
        }
    
        return response()->json(['success' => 'Data saved successfully.']);
    }
    

    public function edit($id)
    {
        $jadwal = Jadwal::find($id);

        return response()->json($jadwal);
    }

    public function destroy($id)
    {
        Jadwal::find($id)->delete();
        return response()->json(['success' => 'Data deleted successfully.']);
    }

    public static function generateJadwalId()
    {
        $lastJadwal = Jadwal::latest('kode_jadwal')->first();

        if (!$lastJadwal) {
            return 'JDW-001'; // If no previous supplier exists, start with SUP-001
        }

        $lastId = intval(substr($lastJadwal->kode_jadwal, 4)); // Extract the numeric portion of the last ID
        $newId = $lastId + 1;
        $paddedNewId = str_pad($newId, 3, '0', STR_PAD_LEFT); // Pad the new ID with leading zeros if necessary
        $generatedId = 'JDW-' . $paddedNewId;

        return $generatedId;
    }

    public function calculateEndTime($startTime, $duration)
    {
        $startTime = Carbon::createFromFormat('H:i', $startTime);
        $endTime = $startTime->copy()->addMinutes($duration);
        return $endTime->format('H:i');
    }

    public function cekJadwalBentrok($jamMulai, $jamBerakhir, $hari, $ruang, $id = null)
    {
        $query = Jadwal::where('hari', $hari)
            ->where('ruang', $ruang)
            ->where(function ($query) use ($jamMulai, $jamBerakhir) {
                $query->where(function ($subQuery) use ($jamMulai, $jamBerakhir) {
                    $subQuery->where('jam_mulai', '<', $jamBerakhir)
                        ->where('jam_berakhir', '>', $jamMulai);
                })
                    ->orWhere(function ($subQuery) use ($jamMulai, $jamBerakhir) {
                        $subQuery->where('jam_mulai', '>=', $jamMulai)
                            ->where('jam_mulai', '<', $jamBerakhir);
                    })
                    ->orWhere(function ($subQuery) use ($jamMulai, $jamBerakhir) {
                        $subQuery->where('jam_berakhir', '>', $jamMulai)
                            ->where('jam_berakhir', '<=', $jamBerakhir);
                    });
            });

        if ($id) {
            $query->where('id', '!=', $id);
        }

        $existingJadwal = $query->first();

        if ($existingJadwal) {
            return "Jadwal bentrok dengan jadwal yang sudah ada.";
        }

        return null; // Tidak ada bentrok
    }
}

resources/views/jadwal/list-for-user.blade.php
@extends('layout.layout-front')

@section('title')
    {{ 'Jadwal Praktikum' }}
@endsection

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <div class="card mb-4">
                {{-- <div class="card-header">
                    <h5 class="card-title">Jadwal Praktikum</h5>
                </div> --}}
                <div class="card-body">
                    <h5 class="mb-4">Jadwal Praktikum</h5>
                    <table class="table table-striped custom-table mb-0 no-footer" role="grid">
                        <thead>
                            <tr role="row">
                                <th>No.</th>
                                <th>Matakuliah Praktikum</th>
                                <th>Kelas</th>
                                <th>Hari</th>
                                <th>Jam</th>
                                <th>Ruang</th>
                                <th>Durasi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Isi tabel disini -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    // AJAX route for DataTables
    let routeUrl = "{{ route('jadwal-praktikum.index') }}";

    // Column configuration for DataTables
    let columns = [{
            data: 'DT_RowIndex',
            searchable: false
        },
        {
            data: null,
            render: function(data, type, row) {

                return data.kode_matakuliah + ' - ' + data.nama_matakuliah + '';
            },
            name: 'nama_matakuliah',
            searchable: true
        },
        {
            data: 'kelas',
            name: 'kelas'
        },
        {
            data: 'hari',
            name: 'hari'
        },
        {
            data: null,
            render: function(data, type, row) {

                return data.jam_mulai + ' - ' + data.jam_berakhir + '';
            },
            name: 'jam_mulai',
            searchable: true
        },
        {
            data: 'ruang',
            name: 'ruang'
        },
        {
            data: null,
            render: function(data, type, row) {
                // Tambahkan teks "menit" setelah nilai durasi
                return data.durasi + ' Menit';
            }
        }
    ];

    let table = initializeDataTables(routeUrl, columns);

</script>
@endsection

resources/views/jadwal/list.blade.php
@extends('layout.layout-admin')

@section('title')
    {{ 'Jadwal' }}
@endsection

@section('content')
    <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="modal-form">
        <div class="modal-dialog" role="document">
            <form class="form-horizontal">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"></h4>
                        <button type="button" class="close close-btn" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" class="form-control">
                        <div class="form-group">
                            <label for="kode_jadwal">Kode Jadwal</label>
                            <input type="text" name="kode_jadwal" id="kode_jadwal" class="form-control" readonly>
                            <span class="text-danger" id="error-kode_jadwal"></span>
                        </div>

                        <div class="form-group">
                            <label for="name">Pilih Praktikum</label>
                            <select name="kode_praktikum" id="kode_praktikum" class="form-control" required>
                                <option>-- Pilih Praktikum --</option>
                                @foreach ($praktikum as $data)
                                    {{-- @if (!in_array($data['kode_praktikum'], $existingKodePraktikum)) --}}
                                    <option value="{{ $data['kode_praktikum'] }}">
                                        {{ $data['kode_matakuliah'] }} - {{ $data['nama_matakuliah'] }} -
                                        {{ $data['kelas'] }}</option>
                                    {{-- @endif --}}
                                @endforeach
                            </select>
                            <span class="text-danger" id="error-kode_praktikum"></span>
                        </div>
                        <div class="form-group">
                            <label for="hari">Hari</label>
                            <select name="hari" id="hari" class="form-control" required>
                                <option>-- Pilih Hari --</option>
                                <option value="Senin">Senin</option>
                                <option value="Selasa">Selasa</option>
                                <option value="Rabu">Rabu</option>
                                <option value="Kamis">Kamis</option>
                                <option value="Jumat">Jumat</option>
                                <option value="Sabtu">Sabtu</option>
                                <option value="Minggu">Minggu</option>
                            </select>
                            <span class="text-danger" id="error-kelas"></span>
                        </div>
                        <div class="form-group">
                            <label for="name">Jam Mulai Praktikum</label>
                            <div class="input-group date" id="timepicker" data-target-input="nearest">
                                <input type="text" id="jam_mulai" name="jam_mulai"
                                    class="form-control datetimepicker-input" data-target="#timepicker"
                                    placeholder="13:00" />
                                <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="far fa-clock"></i></div>
                                </div>
                            </div>
                            <span class="text-danger" id="error-jam-mulai"></span>
                        </div>
                        <div class="form-group">
                            <label for="ruang">Ruang</label>
                            <select name="ruang" id="ruang" class="form-control" required>
                                <option>-- Pilih Ruang --</option>
                                <option value="Lab MSI">LAB MSI</option>
                                <option value="Lab RPL">LAB RPL</option>
                            </select>
                            <span class="text-danger" id="error-ruang"></span>
                        </div>
                        <div class="form-group">
                            <label for="jumlah_pertemuan">Jumlah Pertemuan</label>
                            <select name="durasi" id="durasi" class="form-control" required>
                                <option>-- Pilih Jumlah Pertemuan --</option>
                                <option value="160">16 Pertemuan</option>
                                <option value="170">15 Pertemuan</option>
                                <option value="200">14 Pertemuan</option>
                            </select>
                            <span class="text-danger" id="error-ruang"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-warning close-btn" data-dismiss="modal"><i
                                class="fa fa-arrow-circle-left"></i> Cancel</button>
                        <button type="submit" class="btn btn-sm btn-primary" id="saveBtn"><i class="fa fa-save"></i>
                            Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-outline card-warning">
                        <div class="card-body">
                            <div class="d-flex justify-content-between mb-4">
                                <div class="d-flex justify-content-start" id="print">
                                    <!-- Second div content (if any) -->
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="button" onclick="addForm()" class="btn btn-warning">
                                        <i class="fa fa-plus"></i> Tambah Jadwal
                                    </button>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped custom-table mb-0 no-footer" role="grid">
                                    <thead>
                                        <tr role="row">
                                            <th>#</th>
                                            <th>Kode Jadwal</th>
                                            <th>Nama Praktikum</th>
                                            <th>Kelas</th>
                                            <th>Hari</th>
                                            <th>Jam</th>
                                            <th>Ruang</th>
                                            <th>Durasi</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
    <script>
        // $('#jam_mulai').timepicker({
        //     uiLibrary: 'bootstrap4',
        //     format: 'HH:MM',
        //     mode: '24hr'
        // });

        //     //Timepicker
        // $('#timepicker').datetimepicker({
        // format: 'LT'
        // })

        $(function() {

            //Timepicker
            $('#timepicker').datetimepicker({
                format: 'HH:mm'
            })

        })
        // AJAX route for DataTables
        let routeUrl = "{{ route('jadwal.index') }}";

        // Column configuration for DataTables
        let columns = [{
                data: 'DT_RowIndex',
                searchable: false
            },
            {
                data: 'kode_jadwal',
                name: 'kode_jadwal'
            },
            {
                data: null,
                render: function(data, type, row) {
                    // Gabungkan data 'nama_matakuliah', 'kode_praktikum', dan 'kode_matakuliah' dalam satu kolom
                    return data.kode_matakuliah + ' - ' + data.nama_matakuliah + '';
                },
                searchable: true, // Aktifkan pencarian pada kolom hasil render
                name: 'kode_matakuliah', // Nama kolom yang digunakan untuk pencarian
                name: 'nama_matakuliah',
                searchable: true // Aktifkan pencarian pada kolom nama_matakuliah
            },
            {
                data: 'kelas',
                name: 'kelas'
            },
            {
                data: 'hari',
                name: 'hari'
            },
            {
            data: null,
            render: function(data, type, row) {

                return data.jam_mulai + ' - ' + data.jam_berakhir + '';
            },
            name: 'jam_mulai',
            searchable: true
        },
            {
                data: 'ruang',
                name: 'ruang'
            },
            {
                data: null,
                render: function(data, type, row) {
                    // Tambahkan teks "menit" setelah nilai durasi
                    return data.durasi + ' Menit';
                }
            },
            {
                data: 'aksi',
                name: 'aksi',
                orderable: false,
                searchable: false
            }
        ];

        let table = initializeDataTables(routeUrl, columns);


        $('body').on('click', '.editData', function() {
            var id = $(this).data('id');
            $.get("{{ route('jadwal.index') }}" + '/' + id + '/edit', function(data) {
                $('.modal-title').text('Edit Data');
                $('#modal-form').modal('show');
                $('#id').val(data.id);
                $('#kode_praktikum').val(data.kode_praktikum);
                $('#hari').val(data.hari);
                $('#jam_mulai').val(data.jam_mulai);
                $('#ruang').val(data.ruang);
                $('#durasi').val(data.durasi);

                // Tampilkan form kode_praktikum pada mode edit
                $('#kode_jadwal').prop('hidden', false).val(data.kode_jadwal);

                // // Fokus ke input kode_matakuliah saat mode edit
                // $('#modal-form [name=kode_matakuliah').focus();

                // Tampilkan label kode_praktikum pada mode tambah data
                $('#modal-form label[for="kode_jadwal"]').show();
            });
        });

        function addForm() {
            $("#modal-form").modal('show');
            $('#id').val('');
            $('.modal-title').text('Tambah Data');
            $('#modal-form form')[0].reset();
            $('#modal-form [name=kode_praktikum').focus();
            $('#modal-form [name=hari').focus();
            $('#modal-form [name=jam_mulai').focus();
            $('#modal-form [name=ruang').focus();
            $('#modal-form [name=durasi').focus();

            // Sembunyikan label kode_praktikum pada mode edit
            $('#modal-form label[for="kode_jadwal"]').hide();

            // Sembunyikan form kode_praktikum pada mode tambah data
            $('#kode_jadwal').prop('hidden', true).val('');
        }

        function validation(data, isCreate) {
            let formIsValid = true;
            $('span[id^="error"]').text('');
            if (!data.kode_praktikum) {
                formIsValid = false;
                $("#error-kode_praktikum").text('Praktikum wajib dipilih.')
            }
            return formIsValid;
        }
    </script>
@endsection