routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PemasokController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\DetailKondisiController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\AsistenLabController;
use App\Http\Controllers\AsistenList;
use App\Http\Controllers\PraktikumController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\JadwalUserController;
use App\Http\Controllers\PengajuanJadwalController;
use App\Http\Controllers\ProfileAslabController;
use App\Http\Controllers\BapController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\BapPraktikumController;
use App\Models\Mahasiswa;
use Illuminate\Support\Facades\Auth;
use App\Models\Matakuliah;
use App\Models\PengajuanJadwal;
use App\Models\Praktikum;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::view('/', 'landingpage.index');

Route::get('/', [LandingPageController::class, 'index'])->name('index');

Route::view('/about', 'landingpage/about')->name('about');
Route::view('/contact', 'landingpage/contact')->name('contact');
Route::view('/error', 'errors.403')->name('error.403');

// Route::get('/login', function () {
//     return view('auth.login');
// })->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::view('/', 'landingpage/index')->name('index');
// Route::view('/about', 'landingpage/about')->name('about');
// Route::view('/contact', 'landingpage/contact')->name('contact');
// Route::view('/error', 'errors.403')->name('error.403');


Route::get('/login', function () {
    if (Auth::check()) {
        return redirect()->route('index'); // Redirect to home page
    } else {
        return view('auth.login');
    }
})->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::get('/jadwal-praktikum', [JadwalUserController::class, 'index'])->name('jadwal-praktikum');
Route::resource('jadwal-praktikum', JadwalUserController::class);
Route::resource('asisten', AsistenList::class);

Route::group(['middleware' => ['auth']], function () {
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA'])->group(function () {
    Route::resource('pengguna', PenggunaController::class);

    Route::resource('dosen', DosenController::class);

    Route::resource('matakuliah', MatakuliahController::class);

    Route::resource('aslab', AsistenLabController::class);

    Route::resource('detail-kondisi', DetailKondisiController::class, ['except' => [
        'create', 'update', 'show'
    ]]);
    Route::resource('inventory', InventoryController::class, ['except' => [
        'create', 'update', 'show'
    ]]);

    Route::resource('pemasok', PemasokController::class);

    Route::resource('mahasiswa', MahasiswaController::class);

    Route::resource('kategori', KategoriBarangController::class);

    Route::get('kategori', [KategoriBarangController::class, 'list_categories'])->name('kategori.list');

    Route::get('tambah-barang', [InventoryController::class, 'add']);
    Route::post('tambah-barang/save', [InventoryController::class, 'save']);
    Route::get('edit-barang/{id}', [InventoryController::class, 'edit']);
    Route::get('detail-barang/{id}', [InventoryController::class, 'detail']);
    Route::delete('delete-barang/{id}', [InventoryController::class, 'delete']);
    Route::get('detail-kondisi/{id}', [InventoryController::class, 'detail_kondisi']);
    Route::delete('delete-all-detail-kondisi/{id_barang}/{id}', [InventoryController::class, 'delete_all_detail_kondisi']);
    Route::post('add-detail-kondisi/{id}', [InventoryController::class, 'add_detail_kondisi']);

    Route::get('pengguna/export', [PenggunaController::class, 'export'])->name('pengguna.export');
    Route::post('pengguna/import', [PenggunaController::class, 'import'])->name('pengguna.import');

    Route::post('matakuliah/import', [MatakuliahController::class, 'import'])->name('matakuliah.import');
    // Route::get('jadwal', [JadwalController::class, 'index']);
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN'])->group(function () {

    Route::get('profile-aslab', [ProfileAslabController::class, 'index'])->name('profile.aslab');
    // Route::get('profile-aslab/{id}',[ProfileAslabController::class, 'edit'])->name('profile.aslab.update');
    Route::put('/profile-aslab/{id}', [ProfileAslabController::class, 'edit'])->name('profile.aslab.update');

    // Route::post('profile-aslab',[AsistenLabController::class],'profileEditAslab');

    Route::get('/getKodePraktikum/{nrp}/{id_user}', [PengajuanJadwalController::class, 'getKodePraktikum']);

    Route::resource('pengajuan-jadwal', PengajuanJadwalController::class);
    Route::post('/terima-pengajuan/{id}', [PengajuanJadwalController::class, 'terimaPengajuan'])->name('terima.pengajuan');
    Route::post('/tolak-pengajuan/{id}', [PengajuanJadwalController::class, 'tolakPengajuan'])->name('tolak.pengajuan');
    Route::post('/tambah-jadwal/{id}', [PengajuanJadwalController::class, 'tambahJadwal'])->name('tambah.jadwal');

 
    // Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    // Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
   
    // Route::get('/bap', [BapPraktikumController::class, 'index'])->name('bap-praktikum.list');
    // Route::get('/bap/{kode_praktikum}', [BapPraktikumController::class, 'listBap'])->name('bap-praktikum.list');
    // Route::post('/bap/store', [BapPraktikumController::class, 'storeBap'])->name('bap-praktikum.store');
    // Route::delete('/bap/delete/{id}', [BapPraktikumController::class, 'deleteBap'])->name('bap-praktikum.delete');
    // Route::post('bap/validate/asisten', [BapPraktikumController::class, 'validateAsisten'])->name('validasi.asisten');
    // Route::post('bap/validate/mahasiswa', [BapPraktikumController::class, 'validateMhs'])->name('validasi.mahasiswa');


});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,KOORDINATOR'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('jadwal', JadwalController::class);

    Route::resource('praktikum', PraktikumController::class);

    Route::get('/praktikum/asisten/{kode_praktikum}', [PraktikumController::class, 'asisten'])->name('praktikum.asisten');
    Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
 
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN,KOORDINATOR,MAHASISWA'])->group(function () {
    Route::get('/bap', [BapController::class, 'index'])->name('bap.list');
    Route::get('/bap/{kode_praktikum}', [BapController::class, 'list'])->name('bap.topik');
    // Route::post('/bap/store', [BapController::class, 'storeBap'])->name('bap.store');
    // Route::delete('/bap/delete/{id}', [BapController::class, 'deleteBap'])->name('bap.delete');
    Route::post('/bap/validate', [BapController::class, 'validateBap'])->name('bap.validate');
    Route::post('/bap/validateMhs', [BapController::class, 'validateMahasiswa'])->name('bap.validateMhs');
    // Route::get('bap/{id}/edit', [BapController::class, 'edit']);
    Route::resource('bap', BapController::class);
    Route::post('/custom-pdf-data', [BapController::class, 'getCustomPdfData'])->name('custom_pdf_data_endpoint');

});

resources/views/component/footer-user.blade.php
      <!-- Footer-->
      <footer class="bg-dark py-3 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0 text-white">Copyright &copy; {{ now()->year }} Aditama Putra, Team SIP Prodi Sistem Informasi ITENAS</div>
                </div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">Privacy</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Terms</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>

    

resources/views/component/footer.blade.php
 <!-- /.content-wrapper -->
 <footer class="main-footer">
    <strong>Copyright &copy; {{ now()->year }} Aditama Putra, Team SIP <a href="https://www.itenas.ac.id/brosur-program-studi/fti/program-studi-sistem-informasi/">  Prodi Sistem Informasi ITENAS</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 2.0
    </div>
  </footer>

resources/views/component/head-user.blade.php
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Lab IS</title>
    <!-- Favicon-->
    <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/assets/css/styles.css" rel="stylesheet" />
    <link rel="manifest" href="/manifest.json">
    <!-- DataTables -->
    <link rel="stylesheet" href="/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    {{-- <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
  
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet"> --}}

    <style>
        /* Gaya CSS untuk menghitamkan latar belakang carousel */
        .carousel {
            background-color: #000;
            overflow: hidden;
            /* Mengatasi potensi overflow */
        }

        /* Tambahkan gaya CSS untuk teks di tengah carousel */
        .carousel-caption {
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            /* Atur latar belakang menjadi transparan */
            padding: 20px;
            border-radius: 0;
            /* Hapus border-radius */
            width: 70%;
            /* Lebar caption 100% */
            z-index: 2;
            /* Tambahkan z-indeks yang lebih tinggi */
        }


        /* Gaya teks di dalam caption */
        .carousel-caption h1 {
            font-size: 3rem;
            /* Ukuran font teks "SELAMAT DATANG" */
            font-weight: bold;
            /* Teks tebal */
            color: white;
            /* Warna teks */
            font-family: 'Poppins', sans-serif;
        }

        .carousel-caption p {
            font-size: 1.5rem;
            /* Ukuran font teks deskripsi */
            font-weight: 300;
            /* Teks tipis */
            color: white;
            /* Warna teks */
            font-family: 'Poppins', sans-serif;
        }

        /* Gaya responsif untuk teks di dalam caption */
        @media (max-width: 768px) {
            .carousel-caption h1 {
                font-size: 2rem;
            }

            .carousel-caption p {
                font-size: 1rem;
            }
        }

        /* Gaya untuk mengatur ukuran dan crop gambar dalam carousel */
        .carousel-inner img {
            width: 100%;
            /* Lebar gambar penuh carousel */
            height: 100vh;
            /* Tinggi gambar mengisi seluruh tinggi viewport */
            object-fit: cover;
            /* Untuk mengcrop gambar agar sesuai dengan tinggi dan lebar viewport */
        }

        /* Gaya untuk menghitamkan gambar */
        .drk:after {
            content: "";
            display: block;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: black;
            opacity: 0.6;
            z-index: 1;
        }
    </style>

    <style>
        .feature-card {
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 20px;
            border-radius: 5px;
            text-align: center;
            height: 100%;
            opacity: 0;
            transform: translateY(50px);
            transition: opacity 0.5s ease, transform 0.5s ease;
        }

        .feature-card.show {
            opacity: 1;
            /* Menampilkan elemen */
            transform: translateY(0);
            /* Mengembalikan ke posisi semula */
        }

        .feature-card:hover {
            transform: translateY(-5px);
        }

        .feature-icon {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0 auto 20px;
            font-size: 24px;
        }
    </style>

    <style>
        .card {
            border-radius: 15px;
            /* Rounded corners for the card */
        }

        .badge {
            font-size: 11px;
            padding: 6px 8px;
        }

        .shadow {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            /* Adding shadow to the card */
        }

        .card-header {
            text-align: center;
            padding: 6px;
            font-size: 14px;
            font-weight: 600;

        }

        .card-body {
            padding: 15px;
        }

        .asisten-list {
            max-height: 250px;
            /* Tinggi maksimum untuk kartu */
            overflow-y: auto;
            /* Tambahkan scrollbar jika konten lebih panjang dari maksimum */
        }

        .asisten {
            display: flex;
            align-items: center;
            /* Sejajarkan item secara vertikal */
        }

        .nama {
            flex: 1;
            /* Memungkinkan nama_lengkap untuk mengambil ruang tersisa */
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
        }

    </style>


</head>

resources/views/component/head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>ITERATOR - @yield('title')</title>

    <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
    {{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css"> --}}
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/assets/plugins/fontawesome-free/css/all.min.css">
    <!-- IONIC Icons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/assets/dist/css/adminlte.min.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="/assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/select2.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700">
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/assets/plugins/select2/css/select2.min.css">

    {{-- <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="/assets/css/dataTables.bootstrap4.min.css"> --}}
{{-- 
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css"> --}}
    {{-- <link rel="stylesheet" href="plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css"> --}}

    {{-- <link rel="stylesheet" type="text/css" href="plugins/easyui/themes/default/easyui.css">
	<link rel="stylesheet" type="text/css" href="plugins/easyui/themes/icon.css">
	<link rel="stylesheet" type="text/css" href="plugins/easyui/demo/demo.css"> --}}

    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css"> --}}
    {{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/timepicker@1.14.0/jquery.timepicker.min.css"> --}}
    {{-- Felia Notes :
    aku nyisipin csrf token disini buat nanti dipake ngehit data di javascript
    btw komentar ini boleh dihapus kalo mengganggu    
    --}}
    <link rel="manifest" href="/manifest.json">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {{-- Felia Notes :
    coba kalian cari tau tehnik laravel template, biar kodenya ga sepanjang ini jadi bisa lebih pendek ngodingnya
    itu bakal ngambil waktu banyak di awal tapi kedepannya ngoding bisa cepet karna kode jadi lebih sedikit    

    tapi ngambil waktu di awalnya juga ga akan lama sih
    
    oh iya btw komentar ini boleh dihapus kalo mengganggu
    --}}

    <style>
        .resitdc-image-choose {
            position: relative;
            width: 100%;
            height: 30vh;
            border: 1px dashed #dedede;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .resitdc-image-choose .resitdc-image-choose-input {
            position: absolute;
            width: 100% !important;
            height: 100% !important;
            top: 0;
            left: 0;
            opacity: 0;
            cursor: pointer;
        }

        .resitdc-image-choose .resitdc-image-choose-preview::after {
            display: inline-block;
            font: normal normal normal 14px/1 FontAwesome;
            font-size: inherit;
            text-rendering: auto;
            -webkit-font-smoothing: antialiased;
            content: "\f093";
            font-size: 4rem;
            color: #eaeaea;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .resitdc-image-choose .resitdc-image-choose-preview[style^="background-image:"] {
            width: 100%;
            height: 100%;
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
        }

        .resitdc-image-choose .resitdc-image-choose-preview[style^="background-image:"]::after {
            display: none !important;
        }
    </style>
<style>
    /* Set a fixed width for 'asisten' columns */


</style>

resources/views/component/navbar-admin.blade.php
<!-- Navbar -->

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('index') }}" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        </li>
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
        </li>
        <li class="nav-item dropdown user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <img src="/assets/img/user.jpg" class="user-image img-circle elevation-2" alt="User Image">
                <span class="d-none d-md-inline"> {{ auth()->user()->nama_lengkap }}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">

                <li class="user-header bg-warning">
                    <img src="/assets/img/user.jpg" class="img-circle elevation-2" alt="User Image">
                    <p>
                        {{ auth()->user()->nama_lengkap }}
                        <small> {{ auth()->user()->peran_pengguna }}</small>
                    </p>
                </li>

                <li class="user-footer">
                    {{-- <a href="#" class="btn btn-default btn-flat">Profile</a> --}}
                    <a href="{{ route('logout') }}" class="btn btn-default btn-flat float-right">Logout</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/component/navbar-user.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top ">
    <div class="container px-5">
        <a class="navbar-brand" href="{{ route('index') }}"><img width="25" src="/assets/iterator.png" /> ITERATOR</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{{ route('index') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ route('asisten.index') }}">Asisten</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ route('jadwal-praktikum.index') }}">Jadwal Praktikum</a></li>

                <!-- Untuk Auth -->
                @auth
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @if (auth()->user()->peran_pengguna === 'MAHASISWA' || auth()->user()->peran_pengguna === 'ASISTEN'  || auth()->user()->peran_pengguna === 'KOORDINATOR')
                            <li class="nav-item">
                                <a class="nav-link" href="/bap">Dashboard</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="/dashboard">Dashboard</a>
                            </li>
                        @endif
                    </ul>

                </ul>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i> {{ auth()->user()->nama_pengguna }}
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        {{-- <li><a class="dropdown-item" href="#">Profile</a></li> --}}
                        <li><a class="dropdown-item" href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </div>
                <!-- Tampa Auth -->
            @else
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    </li>
                    <li class="nav-item">
                    </li>
                </ul>
                </ul>
                <a class="btn btn-outline-light" href="login" role="button">Login <i class="fa fa-arrow-right"
                        aria-hidden="true"></i></a>
            @endauth
        </div>
    </div>
</nav>