routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PemasokController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\DetailKondisiController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\AsistenLabController;
use App\Http\Controllers\AsistenList;
use App\Http\Controllers\PraktikumController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\JadwalUserController;
use App\Http\Controllers\PengajuanJadwalController;
use App\Http\Controllers\ProfileAslabController;
use App\Http\Controllers\BapController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\BapPraktikumController;
use App\Models\Mahasiswa;
use Illuminate\Support\Facades\Auth;
use App\Models\Matakuliah;
use App\Models\PengajuanJadwal;
use App\Models\Praktikum;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::view('/', 'landingpage.index');

Route::get('/', [LandingPageController::class, 'index'])->name('index');

Route::view('/about', 'landingpage/about')->name('about');
Route::view('/contact', 'landingpage/contact')->name('contact');
Route::view('/error', 'errors.403')->name('error.403');

// Route::get('/login', function () {
//     return view('auth.login');
// })->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::view('/', 'landingpage/index')->name('index');
// Route::view('/about', 'landingpage/about')->name('about');
// Route::view('/contact', 'landingpage/contact')->name('contact');
// Route::view('/error', 'errors.403')->name('error.403');


Route::get('/login', function () {
    if (Auth::check()) {
        return redirect()->route('index'); // Redirect to home page
    } else {
        return view('auth.login');
    }
})->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');

// Route::get('/jadwal-praktikum', [JadwalUserController::class, 'index'])->name('jadwal-praktikum');
Route::resource('jadwal-praktikum', JadwalUserController::class);
Route::resource('asisten', AsistenList::class);

Route::group(['middleware' => ['auth']], function () {
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA'])->group(function () {
    Route::resource('pengguna', PenggunaController::class);

    Route::resource('dosen', DosenController::class);

    Route::resource('matakuliah', MatakuliahController::class);

    Route::resource('aslab', AsistenLabController::class);

    Route::resource('detail-kondisi', DetailKondisiController::class, ['except' => [
        'create', 'update', 'show'
    ]]);
    Route::resource('inventory', InventoryController::class, ['except' => [
        'create', 'update', 'show'
    ]]);

    Route::resource('pemasok', PemasokController::class);

    Route::resource('mahasiswa', MahasiswaController::class);

    Route::resource('kategori', KategoriBarangController::class);

    Route::get('kategori', [KategoriBarangController::class, 'list_categories'])->name('kategori.list');

    Route::get('tambah-barang', [InventoryController::class, 'add']);
    Route::post('tambah-barang/save', [InventoryController::class, 'save']);
    Route::get('edit-barang/{id}', [InventoryController::class, 'edit']);
    Route::get('detail-barang/{id}', [InventoryController::class, 'detail']);
    Route::delete('delete-barang/{id}', [InventoryController::class, 'delete']);
    Route::get('detail-kondisi/{id}', [InventoryController::class, 'detail_kondisi']);
    Route::delete('delete-all-detail-kondisi/{id_barang}/{id}', [InventoryController::class, 'delete_all_detail_kondisi']);
    Route::post('add-detail-kondisi/{id}', [InventoryController::class, 'add_detail_kondisi']);

    Route::get('pengguna/export', [PenggunaController::class, 'export'])->name('pengguna.export');
    Route::post('pengguna/import', [PenggunaController::class, 'import'])->name('pengguna.import');

    Route::post('matakuliah/import', [MatakuliahController::class, 'import'])->name('matakuliah.import');
    // Route::get('jadwal', [JadwalController::class, 'index']);
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN'])->group(function () {

    Route::get('profile-aslab', [ProfileAslabController::class, 'index'])->name('profile.aslab');
    // Route::get('profile-aslab/{id}',[ProfileAslabController::class, 'edit'])->name('profile.aslab.update');
    Route::put('/profile-aslab/{id}', [ProfileAslabController::class, 'edit'])->name('profile.aslab.update');

    // Route::post('profile-aslab',[AsistenLabController::class],'profileEditAslab');

    Route::get('/getKodePraktikum/{nrp}/{id_user}', [PengajuanJadwalController::class, 'getKodePraktikum']);

    Route::resource('pengajuan-jadwal', PengajuanJadwalController::class);
    Route::post('/terima-pengajuan/{id}', [PengajuanJadwalController::class, 'terimaPengajuan'])->name('terima.pengajuan');
    Route::post('/tolak-pengajuan/{id}', [PengajuanJadwalController::class, 'tolakPengajuan'])->name('tolak.pengajuan');
    Route::post('/tambah-jadwal/{id}', [PengajuanJadwalController::class, 'tambahJadwal'])->name('tambah.jadwal');

 
    // Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    // Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
   
    // Route::get('/bap', [BapPraktikumController::class, 'index'])->name('bap-praktikum.list');
    // Route::get('/bap/{kode_praktikum}', [BapPraktikumController::class, 'listBap'])->name('bap-praktikum.list');
    // Route::post('/bap/store', [BapPraktikumController::class, 'storeBap'])->name('bap-praktikum.store');
    // Route::delete('/bap/delete/{id}', [BapPraktikumController::class, 'deleteBap'])->name('bap-praktikum.delete');
    // Route::post('bap/validate/asisten', [BapPraktikumController::class, 'validateAsisten'])->name('validasi.asisten');
    // Route::post('bap/validate/mahasiswa', [BapPraktikumController::class, 'validateMhs'])->name('validasi.mahasiswa');


});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,KOORDINATOR'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('jadwal', JadwalController::class);

    Route::resource('praktikum', PraktikumController::class);

    Route::get('/praktikum/asisten/{kode_praktikum}', [PraktikumController::class, 'asisten'])->name('praktikum.asisten');
    Route::post('/praktikum/store-asisten',  [PraktikumController::class, 'storeAsisten'])->name('praktikum.storeAsisten');
    Route::delete('/praktikum/delete-asisten/{id}',  [PraktikumController::class, 'deleteAsisten'])->name('praktikum.deleteAsisten');
 
});

Route::middleware(['auth', 'role:TEKNISI,KEPALA,ASISTEN,KOORDINATOR,MAHASISWA'])->group(function () {
    Route::get('/bap', [BapController::class, 'index'])->name('bap.list');
    Route::get('/bap/{kode_praktikum}', [BapController::class, 'list'])->name('bap.topik');
    // Route::post('/bap/store', [BapController::class, 'storeBap'])->name('bap.store');
    // Route::delete('/bap/delete/{id}', [BapController::class, 'deleteBap'])->name('bap.delete');
    Route::post('/bap/validate', [BapController::class, 'validateBap'])->name('bap.validate');
    Route::post('/bap/validateMhs', [BapController::class, 'validateMahasiswa'])->name('bap.validateMhs');
    // Route::get('bap/{id}/edit', [BapController::class, 'edit']);
    Route::resource('bap', BapController::class);
    Route::post('/custom-pdf-data', [BapController::class, 'getCustomPdfData'])->name('custom_pdf_data_endpoint');

});

app/Models/DetailKondisi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DetailKondisi extends Model
{
    use HasFactory;
    protected $table = "detail_kondisi";
    protected $fillable = [
        'nama_kondisi',
        'keterangan_kodisi',
    ];

}

app/Http/Controllers/DetailKondisiController.php
<?php

namespace App\Http\Controllers;

use App\Models\DetailKondisi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\Facades\DataTables;

class DetailKondisiController extends Controller
{
    public function index(Request $request)
    {
        $data = DetailKondisi::all();
        if ($request->ajax()) {
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('aksi', function ($row) {
                    $btn = '<a href="javascript:void(0)" data-id="' . $row->id . '" class="edit btn btn-warning btn-sm editData"><i class="fa fa-edit"></i>&nbsp;Edit</a>';

                    $btn .= ' <a href="javascript:void(0)" data-id="' . $row->id . '" class="btn btn-danger btn-sm deleteData" data-url="' . route('detail-kondisi.store') . '"><i class="fa fa-trash"></i>&nbsp;Delete</a>';

                    return $btn;
                })
                ->rawColumns(['aksi'])
                ->make(true);
        }

        return view('detailkondisi.list');
    }

    public function store(Request $request)
    {
        if (!empty($request->id)) {
            $data = DetailKondisi::find($request->id);
            $data->nama_kondisi = $request->nama_kondisi;
            $data->keterangan_kondisi = $request->keterangan_kondisi;
            $data->save();
        } else {
            $detailKondisi = new DetailKondisi;
            $detailKondisi->nama_kondisi = $request->nama_kondisi;
            $detailKondisi->keterangan_kondisi = $request->keterangan_kondisi;
            $detailKondisi->save();
        }

        return response()->json(['success' => 'Data saved successfully.']);
    }

    public function edit($id)
    {
        $detail_kondisi = DetailKondisi::find($id);
        return response()->json($detail_kondisi);
    }

    public function destroy($id)
    {
        DetailKondisi::find($id)->delete();
        return response()->json(['success' => 'Data deleted successfully.']);
    }
}

resources/views/detailkondisi/list.blade.php
@extends('layout.layout-admin')

@section('title')
    {{ 'Kondisi' }}
@endsection

@section('content')
    <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="modal-form">
        <div class="modal-dialog" role="document">
            <form class="form-horizontal">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"></h4>
                        <button type="button" class="close close-btn" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" class="form-control">
                        <div class="form-group">
                            <label for="name">Nama Kondisi</label>
                            <input type="text" name="nama_kondisi" id="nama_kondisi" class="form-control" autofocus>
                            <span class="text-danger" id="error-nama_kondisi"></span>
                        </div>
                        <div class="form-group">
                            <label for="name">Keterangan Kondisi</label>
                            <textarea name="keterangan_kondisi" id="keterangan_kondisi" class="form-control"></textarea>
                            <span class="text-danger" id="error-keterangan_kondisi"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-flat btn-primary" id="saveBtn"><i
                                class="fa fa-save"></i> Save</button>
                        <button type="button" class="btn btn-sm btn-flat btn-warning close-btn" data-dismiss="modal"><i
                                class="fa fa-arrow-circle-left"></i> Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-outline card-warning">
                        <div class="card-body">
                            <div class="d-flex justify-content-between mb-4">
                                <div class="d-flex justify-content-start" id="print">
                                    <!-- Second div content (if any) -->
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="button" onclick="addForm()" class="btn btn-warning">
                                        <i class="fa fa-plus"></i> Tambah Kondisi
                                    </button>
                                </div>

                            </div>

                            <div class="table-responsive">
                                <table class="table table-striped custom-table mb-0 no-footer" role="grid">
                                    <thead>
                                        <tr role="row">
                                            <th>#</th>
                                            <th>Nama Kondisi</th>
                                            <th>Keterangan Kondisi</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
    <script>
        let routeUrl = "{{ route('detail-kondisi.index') }}";

        let columns = [{
                data: 'DT_RowIndex',
                searchable: false,
                orderable: true,
            },
            {
                data: 'nama_kondisi',
                name: 'nama_kondisi',
            },
            {
                data: 'keterangan_kondisi',
                name: 'keterangan_kondisi',
            },
            {
                data: 'aksi',
                name: 'aksi',
                orderable: false,
                searchable: false
            }
        ];

        let table = initializeDataTables(routeUrl, columns);


        $('body').on('click', '.editData', function() {
            var id = $(this).data('id');
            $.get("{{ route('detail-kondisi.index') }}" + '/' + id + '/edit', function(data) {
                $('.modal-title').text('Edit Data');
                $('#modal-form').modal('show');
                $('#id').val(data.id);
                $('#nama_kondisi').val(data.nama_kondisi);
                $('#keterangan_kondisi').val(data.keterangan_kondisi);
            })
        });

        function addForm() {
            $("#modal-form").modal('show');
            $('#id').val('');
            $('.modal-title').text('Tambah Data');
            $('#modal-form form')[0].reset();
            $('#modal-form [name=nama_kondisi').focus();
        }

        function validation(data, isCreate) {
            let formIsValid = true;
            $('span[id^="error"]').text('');
            if (!data.nama_kondisi) {
                formIsValid = false;
                $("#error-nama_kondisi").text('Nama kondisi wajib diisi.')
            }
            return formIsValid;
        }
    </script>
@endsection